# This configuration is intended for development purpose
name: dev-sample-webmvc-dashboard
services:
  postgresql:
    image: postgres:16.6
    container_name: iqkv-postgres
    restart: unless-stopped
    # volumes:
    #   - ~/volumes/sample-webmvc-dashboard /postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=mydatabase
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432

  mailhog:
    image: mailhog/mailhog
    container_name: iqkv-mailhog
    restart: unless-stopped
    ports:
      - "25:1025"
      - "8025:8025"
